### ISSUE TITLE
Running with Android project

### ISSUE THREAD

**Issue by luiscruz** [walkmod/walkmod-gradle-plugin#3]
I'm trying to apply walkmod to an Android project.
It builds with success but when I apply walkmod it fails:

```
Total time: 7.15 secs
Missing property storeFile
ERROR [main] - Invalid configuration
java.lang.NumberFormatException: For input string: "'android-23'"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:569)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.getCompileAndroidSDKVersion(ClassLoaderConfigurationProvider.java:245)
        at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.getClassPathFiles(ClassLoaderConfigurationProvider.java:332)
        at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.load(ClassLoaderConfigurationProvider.java:535)
        at org.walkmod.impl.DefaultConfigurationAdapter.prepare(DefaultConfigurationAdapter.java:55)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:76)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:81)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:330)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:171)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:196)
```

Apparently the error seems to be project specific, but I am able to build the project, which makes me believe there's something wrong when I run Walkmod.

Here's my procedure:

```
walkmod add java-formatter
walkmod add-provider gradle
walkmod apply -e
```

Any idea?

**Comment by rpau** [comment]
Hi, 

java-formatter is not a transformation. It is purely a writer and walkmod requires at least one transformation.

However, in this case we are reading the compileSdkVersion property, and it expects an integer, as the android specification reports: https://developer.android.com/guide/topics/manifest/uses-sdk-element.html

Walkmod requires to load the classpath of the android application to execute those code transformation that requires symbol resolution (e.g which are the unused methods?)

In you case, if you do not have simultaneously a pom.xml and a build.gradle, the gradle plugin is automatically applied (ONLY) when it is necessary by the selected transformations.

**Comment by rpau** [comment]
The current deployed version fixes that issue. If you run again walkmod, it is fixed.
