### ISSUE TITLE
Is flavor mandatory for Android projects?

### ISSUE THREAD

**Issue by luiscruz** [walkmod/walkmod-gradle-plugin#4]
I'm trying to apply walkmod in an Android project that does not have flavors specified in its gradle configuration.
I've added this plugin as follows:

```
walkmod add-provider gradle
```

However, I'm getting the following error after running `apply -e`:

```
[...]
BUILD SUCCESSFUL

Total time: 3.867 secs
ERROR [main] - Invalid configuration
org.walkmod.conf.ConfigurationException: Please, select one flavour with the command: walkmod add-provider -Dflavor="YOUR_FLAVOR" gradle
        at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.getClassPathFiles(ClassLoaderConfigurationProvider.java:313)
        at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.load(ClassLoaderConfigurationProvider.java:535)
        at org.walkmod.impl.DefaultConfigurationAdapter.prepare(DefaultConfigurationAdapter.java:55)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:76)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:81)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:330)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:171)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:196)
```

**Comment by luiscruz** [comment]
I've tried with different Android projects and I get the same issue. Is there a way to apply it without specifying flavor?

**Comment by rpau** [comment]
Hi,

Yes, but in this case, the plugin checks if the folder intermediates/classes/release/ exists, which is the folder we are assuming as a default compilation folder. Is not your case?

**Comment by luiscruz** [comment]
Running Walkmod inside the `app` directory did the trick. Thanks
