### ISSUE TITLE
unable to run walkmod checkstyle plugin on android project

### ISSUE THREAD

**Issue by ttelang** [walkmod/walkmod-gradle-plugin#5]
On runnning the **walkmod apply** with the following _walkmod.xml_, I am Invalid configuration error as below:

```
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD" "http://www.walkmod.com/dtd/walkmod-1.1.dtd">
<walkmod>
    <conf-providers>
        <conf-provider type="gradle">
            <param name="flavor">myflavor</param>
        </conf-provider>
    </conf-providers>
    <transformation type="imports-cleaner"/>
    <transformation type="checkstyle"/>
</walkmod>
```

```
ERROR [main] - Invalid configuration
java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replaceAll(String.java:2223)
	at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.resolveArtifacts(ClassLoaderConfigurationProvider.java:456)
	at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.getClassPathFiles(ClassLoaderConfigurationProvider.java:342)
	at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.load(ClassLoaderConfigurationProvider.java:535)
	at org.walkmod.impl.DefaultConfigurationAdapter.prepare(DefaultConfigurationAdapter.java:55)
	at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:76)
	at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:81)
	at org.walkmod.WalkModFacade.apply(WalkModFacade.java:330)
	at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
	at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:171)
	at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:196)
```
Please advice how can I rectify this.

**Comment by rpau** [comment]
Hi,

This is a Windows problem, because the character used as File separator, requires an escape character. Let me fix it and I will notify you.

**Comment by ttelang** [comment]
Thanks for the quick response.

**Comment by rpau** [comment]
The current deployed version fixes that issue. If you run again walkmod, it is fixed.
