### ISSUE TITLE
ArrayIndexOutOfBoundsException: 2 on ClassLoaderConfigurationProvider.resolveArtifacts

### ISSUE THREAD

**Issue by sandeepunnao** [walkmod/walkmod-gradle-plugin#6]
I'm trying to apply walkmod in an Android project.

walkmod.xml 
`<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD" "http://www.walkmod.com/dtd/walkmod-1.1.dtd">
<walkmod>
    <modules>
        <module>wibmoSDK</module>
        <module>appvirality</module>
        <module>mobile</module>
        <module>wibmosdklib</module>
    </modules>
    <conf-providers>
        <conf-provider type="gradle"/>
    </conf-providers>
    <transformation type="imports-cleaner"/>
    <transformation type="sonar:AddCurlyBrackets"/>
    <transformation type="sonar:AddSwitchDefaultCase"/>
    <transformation type="sonar:ArrayDesignatorOnType"/>
    <transformation type="sonar:CollapsibleIfStatements"/>
    <transformation type="sonar:DeclarationsShouldUseCollectionInterfaces"/>
    <transformation type="sonar:LocalVarsShouldComplyWithNamingConvention"/>
    <transformation type="sonar:PrimitiveInstantiationForToString"/>
    <transformation type="sonar:RedundantCastsShouldNotBeUsed"/>
    <transformation type="sonar:RemoveCodeComment"/>
    <transformation type="sonar:RemoveEmptyMethod"/>
    <transformation type="sonar:RemoveEmptyStatement"/>
    <transformation type="sonar:RemoveLiteralBoolean"/>
    <transformation type="sonar:RemoveUnusedMethodParameters"/>
    <transformation type="sonar:RemoveUselessImports"/>
    <transformation type="sonar:RemoveUselessParentheses"/>
    <transformation type="sonar:RemoveUselessVariables"/>
    <transformation type="sonar:StaticInitializedFieldToFinal"/>
    <transformation type="sonar:StringCheckOnLeft"/>
    <transformation type="sonar:UseCollectionIsEmpty"/>
    <transformation type="sonar:UseStringEquals"/>
    <transformation type="sonar:VariableImmediatelyReturned"/>
</walkmod>
`

Output is 
`ERROR [main] - Invalid configuration
java.lang.ArrayIndexOutOfBoundsException: 2
        at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.resolveArtifacts(ClassLoaderConfigurationProvider.java:442)
        at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.getClassPathFiles(ClassLoaderConfigurationProvider.java:342)
        at org.walkmod.gradle.providers.ClassLoaderConfigurationProvider.load(ClassLoaderConfigurationProvider.java:535)
        at org.walkmod.impl.DefaultConfigurationAdapter.prepare(DefaultConfigurationAdapter.java:55)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:76)
        at org.walkmod.conf.ConfigurationManager.<init>(ConfigurationManager.java:81)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:330)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:171)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:196)
`

**Comment by rpau** [comment]
The current deployed version fixes that issue. If you run again walkmod, it is fixed.
